const api=p=>fetch('/api'+p).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Erreur');return d});
const $=s=>document.querySelector(s);const title=$('#title');const content=$('#content');
const names={dashboard:'Tableau de bord',posts:'Publications',calendar:'Calendrier',ai:'Assistant IA',media:'Médias',meta:'Comptes sociaux',brand:'Marque DTech'};
async function view(v){title.textContent=names[v];document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));if(v==='dashboard')return dashboard();if(v==='posts')return posts();if(v==='calendar')return calendar();if(v==='ai')return ai();if(v==='media')return media();if(v==='meta')return meta();return brand()}
async function dashboard(){const d=await api('/dashboard/summary');content.innerHTML=`<div class="grid"><div class="card"><label>PUBLICATIONS</label><div class="metric">${d.posts.total}</div></div><div class="card"><label>PROGRAMMÉES</label><div class="metric">${d.posts.scheduled}</div></div><div class="card"><label>ENGAGEMENT</label><div class="metric">${d.engagement.rate}%</div></div><div class="card"><label>MÉDIAS</label><div class="metric">${d.media}</div></div></div><div class="panel"><h3>Infrastructure</h3><div class="row"><span>Cloudflare Worker</span><span class="badge">ACTIF</span></div><div class="row"><span>PostgreSQL / Hyperdrive</span><span class="badge">À CONFIGURER</span></div><div class="row"><span>R2 Storage</span><span class="badge">À CRÉER</span></div><div class="row"><span>Meta</span><span class="badge">À CONFIGURER</span></div></div>`}
async function posts(){const p=await api('/posts');content.innerHTML=`<div class="panel"><button onclick="view('ai')">✦ Nouvelle publication</button>${p.length?p.map(x=>`<div class="row"><span><b>${x.title}</b><br><small>${(x.platforms||[]).join(', ')}</small></span><span class="badge">${x.status}</span></div>`).join(''):'<p>Aucune publication pour le moment.</p>'}</div>`}
function calendar(){content.innerHTML='<div class="panel"><h3>Calendrier éditorial</h3><p>La programmation sera reliée à la base PostgreSQL et au scheduler dans la prochaine configuration serveur.</p></div>'}
function ai(){content.innerHTML='<div class="panel"><h3>Assistant IA DTech</h3><div class="form"><input id="topic" placeholder="Sujet de la publication"><select id="platform"><option>instagram</option><option>facebook</option><option>linkedin</option></select><select id="tone"><option>professionnel</option><option>pédagogique</option><option>commercial</option><option>inspirant</option></select><button onclick="generatePost()">Générer</button><textarea id="out" placeholder="Résultat..."></textarea></div></div>'}
async function generatePost(){const r=await api('/ai/generate');}
window.generatePost=async()=>{const r=await fetch('/api/ai/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({topic:$('#topic').value,platform:$('#platform').value,tone:$('#tone').value})}).then(x=>x.json());$('#out').value=JSON.stringify(r,null,2)};
async function meta(){const s=await api('/meta/status');$('#metaStatus').textContent=s.configured?'Configuré':'Non configuré';content.innerHTML=`<div class="panel"><h3>Facebook + Instagram</h3><div class="row"><span>Application Meta</span><span class="badge">${s.configured?'CONFIGURÉE':'À CONFIGURER'}</span></div><button onclick="location.href='/api/meta/oauth/start'">Connecter Meta</button><p>Les secrets restent côté serveur. OAuth et état anti-CSRF sont gérés par le backend.</p></div>`}
function media(){content.innerHTML='<div class="panel"><h3>Bibliothèque média</h3><p>Le bucket R2 sera utilisé pour les images et vidéos.</p></div>'}
async function brand(){const b=await api('/brand');content.innerHTML=`<div class="panel"><h3>${b.name}</h3><p><b>${b.slogan}</b></p><p>${b.description}</p></div>`}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>view(b.dataset.view));$('#generate').onclick=()=>view('ai');view('dashboard');
